<?php
  $servers = [
    'FileName ' => $_SERVER['PHP_SELF'],
    'Gateway ' => $_SERVER['GATEWAY_INTERFACE'],
    'IP adress of the server ' => $_SERVER['SERVER_ADDR'],
    'Server Host Name ' => $_SERVER['SERVER_NAME'],
    'Server Software Name ' => $_SERVER['SERVER_SOFTWARE'],
    'Server Protocol ' => $_SERVER['SERVER_PROTOCOL'],
    'Which request method use ' => $_SERVER['REQUEST_METHOD'],
    'Timestamp start of the request ' => $_SERVER['REQUEST_TIME'],
    'Document Root Directory ' => $_SERVER['DOCUMENT_ROOT'],
    'Contents of the Accept ' => $_SERVER['HTTP_ACCEPT'],
    'Contents of the Accept-Encoding ' => $_SERVER['HTTP_ACCEPT_ENCODING'],
    'Contents of the Accept-Language ' => $_SERVER['HTTP_ACCEPT_LANGUAGE'],
    'Contents of the Connection ' => $_SERVER['HTTP_CONNECTION'],
    'Contents of the Host ' => $_SERVER['HTTP_HOST'],
    'Contents of the User-Agent ' => $_SERVER['HTTP_USER_AGENT'],
    'The IP address from which the user is viewing the current page ' => $_SERVER['REMOTE_ADDR'],
    'The port being used on the user\'s machine to communicate with the web server ' => $_SERVER['REMOTE_PORT'],
    'The absolute pathname ' => $_SERVER['SCRIPT_FILENAME'],
    'Directive in the web server configuration file ' => $_SERVER['SERVER_ADMIN'],
    'The port on the server machine ' => $_SERVER['SERVER_PORT'],
    'String containing the server version ' => $_SERVER['SERVER_SIGNATURE'],
    'Contains the current script\'s path ' => $_SERVER['SCRIPT_NAME'],
    'The URI which was given in order to access this page ' => $_SERVER['REQUEST_URI'],
    // 'The address of the page ' => $_SERVER['HTTP_REFERER'],
    // 'When doing Digest HTTP authentication ' => $_SERVER['PHP_AUTH_DIGEST'],
    // 'When doing HTTP authentication(username provided) ' => $_SERVER['PHP_AUTH_USER'],
    // 'When doing HTTP authentication(password provided) ' => $_SERVER['PHP_AUTH_PW'],
    // 'When doing HTTP authentication(authentication type) ' => $_SERVER['AUTH_TYPE'],
    // 'Contains any client-provided pathname information ' => $_SERVER['PATH_INFO'],
    // 'Original version of \'PATH_INFO\' ' => $_SERVER['ORIG_PATH_INFO']
  ];
?>
